name: proyectoapi

services:

  api:

    build:
      context: .
      dockerfile: ProyectoApi.Api/Dockerfile

    container_name: proyectoapi-api

    ports:
      - "8001:8081"

    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: "http://+:8081"
      ConnectionStrings__DefaultConnection: "Server=${MYSQL_SERVER};Port=${MYSQL_PORT};Database=${MYSQL_DATABASE};User=${MYSQL_USER};Password=${MYSQL_PASSWORD};"
    
    networks:
      - middleware-sqlapi

networks:
  middleware-sqlapi:
    external: true