name: actions-pipeline

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Echo message
        run: |
          echo "Hello, World!"
